const data = {
    products:[
        {
            _id:'1',
            name:'Pineapple',
            category:'Vietnam',
            image:'/images/pd1.jgp',
            price:120,
            brand:'Vietnam',
            rating:4.5,
            numReviews:10,
            description: 'high quality product',
        },
        {
            _id:'2',
            name:'Apple',
            category:'Vietnam',
            image:'/images/pd2.jgp',
            price:120,
            brand:'Vietnam',
            rating:4.5,
            numReviews:10,
            description: 'high quality product',
        },
        {
            _id:'1',
            name:'Pineapple',
            category:'Vietnam',
            image:'/images/pd1.jgp',
            price:120,
            brand:'Vietnam',
            rating:4.5,
            numReviews:10,
            description: 'high quality product',
        },
        {
            _id:'1',
            name:'Pineapple',
            category:'Vietnam',
            image:'/images/pd1.jgp',
            price:120,
            brand:'Vietnam',
            rating:4.5,
            numReviews:10,
            description: 'high quality product',
        },
        {
            _id:'1',
            name:'Pineapple',
            category:'Vietnam',
            image:'/images/pd1.jgp',
            price:120,
            brand:'Vietnam',
            rating:4.5,
            numReviews:10,
            description: 'high quality product',
        }

    ]
}